version: "3"

services:
  sonarqube:
    build: sonarqube
    container_name: sonarqube
    ports:
      - "${LOCALHOST_HTTP_PORT}:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/${DB_NAME}
      - sonar.jdbc.username=${DB_USER}
      - sonar.jdbc.password=${DB_PASS}
    volumes:
      - ${VOLUMES_DIR}/sonarqube_conf:/opt/sonarqube/conf
      - ${VOLUMES_DIR}/sonarqube_data:/opt/sonarqube/data
      - ${VOLUMES_DIR}/sonarqube_extensions:/opt/sonarqube/extensions
      - ${VOLUMES_DIR}/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    build: postgres
    container_name: "sonarqube_postgres"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ${VOLUMES_DIR}/postgres:/var/lib/postgresql
      - ${VOLUMES_DIR}/postgres_data:/var/lib/postgresql/data
    networks:
      - sonarnet

networks:
  sonarnet:

#volumes:
#  sonarqube_conf:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_bundled-plugins:
#  postgresql:
#  postgresql_data:
